theme = 'diary'
title = 'ZZ的筆記'
copyright = 'CC BY 4.0'
DefaultContentLanguage = 'zh-hant'


[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4




googleAnalytics = "G-5G47PFM5MG"


[params]
favicon="/images/avatar.png"
disableToC=true
enableReadingTime=true
subtitle = "我是ZZ，一名前端工程師"
enableLaTeX=true
enableAutoDarkMode=true
googleSearchCode = "https://cse.google.com/cse.js?cx=217a750bd65bc48de"

enableGiscus = true
[params.giscus]
    data-repo="DoubleLazyZ/Blog-Comments"
    data-repo-id="R_kgDOJB5kKw"
    data-category="Announcements"
    data-category-id="DIC_kwDOJB5kK84CUbyH"
    data-mapping="title"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="zh-TW"
    crossorigin="anonymous"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

[taxonomies]
   category = "categories"
   tag = "tags"


